### PR TITLE
Build on Travis CI

### PR DESCRIPTION
**Pull request by floscher**
This change will check each commit, if it introduces errors into the code.
The current status of the code ( or ) is shown in the `README.md` file (see https://github.com/floscher/LandClimTools for how this would look).
Additionally you'll be notified via e-mail if the build status changes.

In order for this to work, you'll need to follow the steps outlined in these [PDF instructions](https://github.com/KIT-IfGG/LandClimTools/files/712147/travis.pdf). After doing this, each and every commit will be analyzed for potential problems.

### CODE REVIEW

**Comment by KDolos** [comment]
cool :-). thank you

**Comment by floscher** [comment]
Can you reopen the pull request? You merged your new changes into my repository, this pull request tried to do it the other way around, merging my changes into your repository :wink: .

**Comment by floscher** [comment]
One thing that you can do, when these changes are merged, is easily [publish releases on GitHub](https://github.com/floscher/LandClimTools/releases) for download.

Steps that have to be done once:
* Go to https://github.com/settings/tokens
* Click on "Generate token", this will ask you to confirm your password
* Enter a meaningful description, like "deploy releases for KIT-IfGG/LandClimTools"
* Check the checkbox next to `public_repo`
* Click on "Generate token"
* Copy the token
* Go to https://travis-ci.org/KIT-IfGG/LandClimTools/settings
* Create a new environment variable with name `GH_TOKEN` and paste your token into the value field. Make sure the switch `Display value in build log` is off and then click on `Add`

These steps allow Travis to upload the releases in your name.
The token is kind of a secondary password for your account, but not with full access. It allows Travis to upload the release to GitHub in your name. So don't tell it to anyone and don't save it anywhere, it's enough when the token is pasted into the environment variable at travis-ci.og, you won't need it anywhere else in the future. 

Then, when you want to release, it's as simple as:
* In your local git-repository checkout the version you want to release
* Enter `git tag v1.2.3` into the command line (make sure the version number matches the number in the `DESCRIPTION` file)
* Do `git push origin v1.2.3`

That's it, a few minutes later the release will be uploaded to your GitHub-repository.

For an example see: https://github.com/floscher/LandClimTools/releases/v1.0.0

**Comment by KDolos** [comment]
i try to reopen... internet help tells, that i have to write a new comment

**Comment by floscher** [comment]
Isn't there a reopen button below? If not I could open a new one.

**Comment by KDolos** [comment]
nooo, cannot reopen this pull request.... "Once a pull request is closed, it is locked forever and cannot be reopened." Hmm...

**Comment by KDolos** [comment]
reopen button is grey

**Pull request closed without merging**
